/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranslateRouteImport } from './routes/translate'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GamesRouteImport } from './routes/games'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClansRouteImport } from './routes/clans'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'
import { Route as GamesWordCatcherRouteImport } from './routes/games.word-catcher'
import { Route as GamesMemoryMatchRouteImport } from './routes/games.memory-match'
import { Route as GamesHangmanRouteImport } from './routes/games.hangman'
import { Route as ClansClanIdRouteImport } from './routes/clans.$clanId'

const TranslateRoute = TranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClansRoute = ClansRouteImport.update({
  id: '/clans',
  path: '/clans',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => TeamsRoute,
} as any)
const GamesWordCatcherRoute = GamesWordCatcherRouteImport.update({
  id: '/word-catcher',
  path: '/word-catcher',
  getParentRoute: () => GamesRoute,
} as any)
const GamesMemoryMatchRoute = GamesMemoryMatchRouteImport.update({
  id: '/memory-match',
  path: '/memory-match',
  getParentRoute: () => GamesRoute,
} as any)
const GamesHangmanRoute = GamesHangmanRouteImport.update({
  id: '/hangman',
  path: '/hangman',
  getParentRoute: () => GamesRoute,
} as any)
const ClansClanIdRoute = ClansClanIdRouteImport.update({
  id: '/$clanId',
  path: '/$clanId',
  getParentRoute: () => ClansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clans': typeof ClansRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/games': typeof GamesRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/teams': typeof TeamsRouteWithChildren
  '/translate': typeof TranslateRoute
  '/clans/$clanId': typeof ClansClanIdRoute
  '/games/hangman': typeof GamesHangmanRoute
  '/games/memory-match': typeof GamesMemoryMatchRoute
  '/games/word-catcher': typeof GamesWordCatcherRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clans': typeof ClansRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/games': typeof GamesRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/teams': typeof TeamsRouteWithChildren
  '/translate': typeof TranslateRoute
  '/clans/$clanId': typeof ClansClanIdRoute
  '/games/hangman': typeof GamesHangmanRoute
  '/games/memory-match': typeof GamesMemoryMatchRoute
  '/games/word-catcher': typeof GamesWordCatcherRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clans': typeof ClansRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/games': typeof GamesRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/teams': typeof TeamsRouteWithChildren
  '/translate': typeof TranslateRoute
  '/clans/$clanId': typeof ClansClanIdRoute
  '/games/hangman': typeof GamesHangmanRoute
  '/games/memory-match': typeof GamesMemoryMatchRoute
  '/games/word-catcher': typeof GamesWordCatcherRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/clans'
    | '/dashboard'
    | '/forgot-password'
    | '/games'
    | '/leaderboard'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/store'
    | '/teams'
    | '/translate'
    | '/clans/$clanId'
    | '/games/hangman'
    | '/games/memory-match'
    | '/games/word-catcher'
    | '/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/clans'
    | '/dashboard'
    | '/forgot-password'
    | '/games'
    | '/leaderboard'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/store'
    | '/teams'
    | '/translate'
    | '/clans/$clanId'
    | '/games/hangman'
    | '/games/memory-match'
    | '/games/word-catcher'
    | '/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/clans'
    | '/dashboard'
    | '/forgot-password'
    | '/games'
    | '/leaderboard'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/store'
    | '/teams'
    | '/translate'
    | '/clans/$clanId'
    | '/games/hangman'
    | '/games/memory-match'
    | '/games/word-catcher'
    | '/teams/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ClansRoute: typeof ClansRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GamesRoute: typeof GamesRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoreRoute: typeof StoreRoute
  TeamsRoute: typeof TeamsRouteWithChildren
  TranslateRoute: typeof TranslateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/translate': {
      id: '/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof TranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clans': {
      id: '/clans'
      path: '/clans'
      fullPath: '/clans'
      preLoaderRoute: typeof ClansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/games/word-catcher': {
      id: '/games/word-catcher'
      path: '/word-catcher'
      fullPath: '/games/word-catcher'
      preLoaderRoute: typeof GamesWordCatcherRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/memory-match': {
      id: '/games/memory-match'
      path: '/memory-match'
      fullPath: '/games/memory-match'
      preLoaderRoute: typeof GamesMemoryMatchRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/hangman': {
      id: '/games/hangman'
      path: '/hangman'
      fullPath: '/games/hangman'
      preLoaderRoute: typeof GamesHangmanRouteImport
      parentRoute: typeof GamesRoute
    }
    '/clans/$clanId': {
      id: '/clans/$clanId'
      path: '/$clanId'
      fullPath: '/clans/$clanId'
      preLoaderRoute: typeof ClansClanIdRouteImport
      parentRoute: typeof ClansRoute
    }
  }
}

interface ClansRouteChildren {
  ClansClanIdRoute: typeof ClansClanIdRoute
}

const ClansRouteChildren: ClansRouteChildren = {
  ClansClanIdRoute: ClansClanIdRoute,
}

const ClansRouteWithChildren = ClansRoute._addFileChildren(ClansRouteChildren)

interface GamesRouteChildren {
  GamesHangmanRoute: typeof GamesHangmanRoute
  GamesMemoryMatchRoute: typeof GamesMemoryMatchRoute
  GamesWordCatcherRoute: typeof GamesWordCatcherRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesHangmanRoute: GamesHangmanRoute,
  GamesMemoryMatchRoute: GamesMemoryMatchRoute,
  GamesWordCatcherRoute: GamesWordCatcherRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface TeamsRouteChildren {
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsTeamIdRoute: TeamsTeamIdRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ClansRoute: ClansRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GamesRoute: GamesRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoreRoute: StoreRoute,
  TeamsRoute: TeamsRouteWithChildren,
  TranslateRoute: TranslateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
